#hibernate settings
datasource:
  url: jdbc:sqlserver://77.47.207.57:10936
  username: TKIK_32
  password: TKIK_32_123
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  dialect: org.hibernate.dialect.SQLServerDialect
  ddl-auto : none
  show-sql : false
  format-sql : true
  db.entitymanager.packages.to.scan: com.kpi.kpi_duties_db.domain

server:
  port: 52300
