#logging
logging:
  file: logs/kpi.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
#    org.hibernate: DEBUG
    com.kpi.kpi_duties_db: INFO

#Base path to jersey controller endpoint

spring:
  jersey:
      application-path: /api
  profiles:
    active: deploy