export const ADD_FORM_SUBMIT_REQUEST = 'SUBMIT_ADD_FORM_SUBMIT_REQUEST';
export const ADD_FORM_SUBMIT_FAIL = 'SUBMIT_ADD_FORM_SUBMIT_FAIL';
export const ADD_FORM_SUBMIT_SUCCESS = 'SUBMIT_ADD_FORM_SUBMIT_SUCCESS';

export const HIDE_ADD_FORM_SERVER_RESP_MSG = 'HIDE_ADD_FORM_SERVER_RESP_MSG';

export const ADD_FORM_OCCUPATION_GROUP_INP_CHANGE = "ADD_FORM_OCCUPATION_GROUP_INP_CHANGE";
export const ADD_FORM_CLARIFICATION_INP_CHANGE = "ADD_FORM_CLARIFICATION_INP_CHANGE";
export const ADD_FORM_CLARIFIED_OCCUP_INP_CHANGE = "ADD_FORM_CLARIFIED_OCCUP_INP_CHANGE";

