export const FETCH_KP_CODES_LIST_REQUEST = 'FETCH_KP_CODES_LIST_REQUEST';
export const FETCH_KP_CODES_LIST_FAIL = 'FETCH_KP_CODES_LIST_FAIL';
export const FETCH_KP_CODES_LIST_SUCCESS = 'FETCH_KP_CODES_LIST_SUCCESS';

export const FETCH_ZKPPTR_CODES_LIST_REQUEST = 'FETCH_ZKPPTR_CODES_LIST_REQUEST';
export const FETCH_ZKPPTR_CODES_LIST_FAIL = 'FETCH_ZKPPTR_CODES_LIST_FAIL';
export const FETCH_ZKPPTR_CODES_LIST_SUCCESS = 'FETCH_ZKPPTR_CODES_LIST_SUCCESS';

export const FETCH_ETDK_CODES_LIST_REQUEST = 'FETCH_ETDK_CODES_LIST_REQUEST';
export const FETCH_ETDK_CODES_LIST_FAIL = 'FETCH_ETDK_CODES_LIST_FAIL';
export const FETCH_ETDK_CODES_LIST_SUCCESS = 'FETCH_ETDK_CODES_LIST_SUCCESS';

export const FETCH_DKHP_CODES_LIST_REQUEST = 'FETCH_DKHP_CODES_LIST_REQUEST';
export const FETCH_DKHP_CODES_LIST_FAIL = 'FETCH_DKHP_CODES_LIST_FAIL';
export const FETCH_DKHP_CODES_LIST_SUCCESS = 'FETCH_DKHP_CODES_LIST_SUCCESS';
