export const ADD_NEW_OCCUP_SUBMIT_REQUEST = 'ADD_NEW_OCCUP_SUBMIT_REQUEST';
export const ADD_NEW_OCCUP_SUBMIT_FAIL = 'ADD_NEW_OCCUP_SUBMIT_FAIL';
export const ADD_NEW_OCCUP_SUBMIT_SUCCESS = 'ADD_NEW_OCCUP_SUBMIT_SUCCESS';

export const ADD_NEW_OCCUP_HIDE_SERVER_RESP_MSG = 'ADD_NEW_OCCUP_HIDE_SERVER_RESP_MSG';

export const ADD_NEW_OCCUP_OCCUPATION_GROUP_INP_CHANGE = "ADD_NEW_OCCUP_OCCUPATION_GROUP_INP_CHANGE";
export const ADD_NEW_OCCUP_CLARIFICATION_INP_CHANGE = "ADD_NEW_OCCUP_CLARIFICATION_INP_CHANGE";
export const ADD_NEW_OCCUP_CLARIFIED_OCCUP_INP_CHANGE = "ADD_NEW_OCCUP_CLARIFIED_OCCUP_INP_CHANGE";

export const ADD_NEW_OCCUP_INP_IS_VIRTUAL_CHANGE = "ADD_NEW_OCCUP_INP_IS_VIRTUAL_CHANGE";
