export const DEL_OCCUP_REQUEST = 'DEL_OCCUP_REQUEST';
export const DEL_OCCUP_FAIL = 'DEL_OCCUP_FAIL';
export const DEL_OCCUP_SUCCESS = 'DEL_OCCUP_SUCCESS';
export const DISMISS_DEL_OCCUP_ALERT = 'DISMISS_DEL_OCCUP_ALERT';
