export const EDIT_OCCUP_SUBMIT_REQUEST = 'EDIT_OCCUP_SUBMIT_REQUEST';
export const EDIT_OCCUP_SUBMIT_FAIL = 'EDIT_OCCUP_SUBMIT_FAIL';
export const EDIT_OCCUP_SUBMIT_SUCCESS = 'EDIT_OCCUP_SUBMIT_SUCCESS';

export const EDIT_OCCUP_HIDE_SERVER_RESP_MSG = 'EDIT_OCCUP_HIDE_SERVER_RESP_MSG';

export const EDIT_OCCUP_OCCUPATION_GROUP_INP_CHANGE = "EDIT_OCCUP_OCCUPATION_GROUP_INP_CHANGE";
export const EDIT_OCCUP_CLARIFICATION_INP_CHANGE = "EDIT_OCCUP_CLARIFICATION_INP_CHANGE";
export const EDIT_OCCUP_CLARIFIED_OCCUP_INP_CHANGE = "EDIT_OCCUP_CLARIFIED_OCCUP_INP_CHANGE";

export const EDIT_OCCUP_INP_IS_VIRTUAL_CHANGE = "EDIT_OCCUP_INP_IS_VIRTUAL_CHANGE";

export const HIDE_MODAL_EDIT_OCCUP = 'HIDE_MODAL_EDIT_OCCUP';
export const SHOW_MODAL_EDIT_OCCUP = 'SHOW_MODAL_EDIT_OCCUP';
