export const FETCH_CLARIFICATION_LIST_REQUEST = 'FETCH_CLARIFICATION_LIST_REQUEST';
export const FETCH_CLARIFICATION_LIST_FAIL = 'FETCH_CLARIFICATION_LIST_FAIL';
export const FETCH_CLARIFICATION_LIST_SUCCESS = 'FETCH_CLARIFICATION_LIST_SUCCESS';

export const FETCH_CLARIFIED_OCCUP_LIST_REQUEST = 'FETCH_CLARIFIED_OCCUP_LIST_REQUEST';
export const FETCH_CLARIFIED_OCCUP_LIST_FAIL = 'FETCH_CLARIFIED_OCCUP_LIST_FAIL';
export const FETCH_CLARIFIED_OCCUP_LIST_SUCCESS = 'FETCH_CLARIFIED_OCCUP_LIST_SUCCESS';

export const FETCH_OCCUP_GROUP_LIST_REQUEST = 'FETCH_OCCUP_GROUP_LIST_REQUEST';
export const FETCH_OCCUP_GROUP_LIST_FAIL = 'FETCH_OCCUP_GROUP_LIST_FAIL';
export const FETCH_OCCUP_GROUP_LIST_SUCCESS = 'FETCH_OCCUP_GROUP_LIST_SUCCESS';

export const ADD_NEW_CLARIFICATION_REQUEST = 'ADD_NEW_CLARIFICATION_REQUEST';
export const ADD_NEW_CLARIFICATION_FAIL = 'ADD_NEW_CLARIFICATION_FAIL';
export const ADD_NEW_CLARIFICATION_SUCCESS = 'ADD_NEW_CLARIFICATION_SUCCESS';
export const DISMISS_MODAL_ADD_NEW_CLARIFICATION_ALERT = 'DISMISS_MODAL_ADD_NEW_CLARIFICATION_ALERT';

export const ADD_NEW_OCCUPATION_GROUP_REQUEST = 'ADD_NEW_OCCUPATION_GROUP_REQUEST';
export const ADD_NEW_OCCUPATION_GROUP_SUCCESS = 'ADD_NEW_OCCUPATION_GROUP_SUCCESS';
export const ADD_NEW_OCCUPATION_GROUP_FAIL = 'ADD_NEW_OCCUPATION_GROUP_FAIL';
export const DISMISS_MODAL_ADD_NEW_OCCUPATION_GROUP_LIST = 'DISMISS_MODAL_ADD_NEW_OCCUPATION_GROUP_LIST';

export const EDIT_CLARIFICATION_REQUEST = 'EDIT_CLARIFICATION_REQUEST';
export const EDIT_CLARIFICATION_FAIL = 'EDIT_CLARIFICATION_FAIL';
export const EDIT_CLARIFICATION_SUCCESS = 'EDIT_CLARIFICATION_SUCCESS';
export const EDIT_CLARIFICATION_CLEAR_MSG = 'EDIT_CLARIFICATION_CLEAR_MSG';

export const EDIT_OCCUPATION_GROUP_REQUEST = 'EDIT_OCCUPATION_GROUP_REQUEST';
export const EDIT_OCCUPATION_GROUP_SUCCESS = 'EDIT_OCCUPATION_GROUP_SUCCESS';
export const EDIT_OCCUPATION_GROUP_FAIL = 'EDIT_OCCUPATION_GROUP_FAIL';
export const EDIT_OCCUPATION_GROUP_CLEAR_MSG = 'EDIT_OCCUPATION_GROUP_CLEAR_MSG';
