export const FETCH_KP_CODES_LIST_REQUEST = 'FETCH_KP_CODES_LIST_REQUEST';
export const FETCH_KP_CODES_LIST_FAIL = 'FETCH_KP_CODES_LIST_FAIL';
export const FETCH_KP_CODES_LIST_SUCCESS = 'FETCH_KP_CODES_LIST_SUCCESS';

export const FETCH_ZKPPTR_CODES_LIST_REQUEST = 'FETCH_ZKPPTR_CODES_LIST_REQUEST';
export const FETCH_ZKPPTR_CODES_LIST_FAIL = 'FETCH_ZKPPTR_CODES_LIST_FAIL';
export const FETCH_ZKPPTR_CODES_LIST_SUCCESS = 'FETCH_ZKPPTR_CODES_LIST_SUCCESS';

export const FETCH_ETDK_CODES_LIST_REQUEST = 'FETCH_ETDK_CODES_LIST_REQUEST';
export const FETCH_ETDK_CODES_LIST_FAIL = 'FETCH_ETDK_CODES_LIST_FAIL';
export const FETCH_ETDK_CODES_LIST_SUCCESS = 'FETCH_ETDK_CODES_LIST_SUCCESS';

export const FETCH_DKHP_CODES_LIST_REQUEST = 'FETCH_DKHP_CODES_LIST_REQUEST';
export const FETCH_DKHP_CODES_LIST_FAIL = 'FETCH_DKHP_CODES_LIST_FAIL';
export const FETCH_DKHP_CODES_LIST_SUCCESS = 'FETCH_DKHP_CODES_LIST_SUCCESS';

export const ADD_NEW_KP_CODE_REQUEST = 'ADD_NEW_KP_CODE_REQUEST';
export const ADD_NEW_KP_CODE_SUCCESS= 'ADD_NEW_KP_CODE_SUCCESS';
export const ADD_NEW_KP_CODE_FAIL= 'ADD_NEW_KP_CODE_FAIL';
export const ADD_NEW_KP_CODE_CLEAR_ERROR = 'ADD_NEW_KP_CODE_CLEAR_ERROR';

export const ADD_NEW_ZKPPTR_CODE_REQUEST = 'ADD_NEW_ZKPPTR_CODE_REQUEST';
export const ADD_NEW_ZKPPTR_CODE_SUCCESS= 'ADD_NEW_ZKPPTR_CODE_SUCCESS';
export const ADD_NEW_ZKPPTR_CODE_FAIL= 'ADD_NEW_ZKPPTR_CODE_FAIL';
export const ADD_NEW_ZKPPTR_CODE_CLEAR_ERROR = 'ADD_NEW_ZKPPTR_CODE_CLEAR_ERROR';

export const ADD_NEW_ETDK_CODE_REQUEST = 'ADD_NEW_ETDK_CODE_REQUEST';
export const ADD_NEW_ETDK_CODE_SUCCESS= 'ADD_NEW_ETDK_CODE_SUCCESS';
export const ADD_NEW_ETDK_CODE_FAIL= 'ADD_NEW_ETDK_CODE_FAIL';
export const ADD_NEW_ETDK_CODE_CLEAR_ERROR = 'ADD_NEW_ETDK_CODE_CLEAR_ERROR';

export const ADD_NEW_DKHP_CODE_REQUEST = 'ADD_NEW_DKHP_CODE_REQUEST';
export const ADD_NEW_DKHP_CODE_SUCCESS= 'ADD_NEW_DKHP_CODE_SUCCESS';
export const ADD_NEW_DKHP_CODE_FAIL= 'ADD_NEW_DKHP_CODE_FAIL';
export const ADD_NEW_DKHP_CODE_CLEAR_ERROR = 'ADD_NEW_DKHP_CODE_CLEAR_ERROR';
