export const SEARCH_OCCUP_BOX_FORM_SUBMIT_REQUEST = 'SEARCH_OCCUP_BOX_FORM_SUBMIT_REQUEST';
export const SEARCH_OCCUP_BOX_FORM_SUBMIT_FAIL = 'SEARCH_OCCUP_BOX_FORM_SUBMIT_FAIL';
export const SEARCH_OCCUP_BOX_FORM_SUBMIT_SUCCESS = 'SEARCH_OCCUP_BOX_FORM_SUBMIT_SUCCESS';
export const DISMISS_SEARCH_OCCUP_BOX_FORM_ALERT = 'DISMISS_SEARCH_OCCUP_BOX_FORM_ALERT';

export const DOWNLOAD_SEARCH_OCCUP_RES_REQUEST = 'DOWNLOAD_SEARCH_OCCUP_RES_REQUEST';
export const DOWNLOAD_SEARCH_OCCUP_RES_SUCCESS = 'DOWNLOAD_SEARCH_OCCUP_RES_SUCCESS';
export const DOWNLOAD_SEARCH_OCCUP_RES_FAIL = 'DOWNLOAD_SEARCH_OCCUP_RES_FAIL';
export const DISMISS_DOWNLOAD_SEARCH_OCCUP_RES_ALERT = 'DISMISS_DOWNLOAD_SEARCH_OCCUP_RES_ALERT';
export const SHOW_MODAL_RES_DOWNLOAD_SETTINGS = 'SHOW_MODAL_RES_DOWNLOAD_SETTINGS';
export const HIDE_MODAL_RES_DOWNLOAD_SETTINGS = 'HIDE_MODAL_RES_DOWNLOAD_SETTINGS';